### ISSUE TITLE
chef blocks no longer seem to work in recent revisions (1.3.17, for example)

### ISSUE THREAD

**Issue by contentfree** [auser/poolparty#54]
In my clouds.rb, I have a block:

chef do
  include_recipes "....."
  # etc
end

But it doesn't work. Instead it returns "undefined method `chef' for #PoolParty::..." - I don't see anything in the docs that reflect the removal of chef support.
